# Generated by Django 5.1.2 on 2024-11-29 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='module',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
