# Generated by Django 5.1.2 on 2024-10-28 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trainer',
        ),
    ]
