# Generated by Django 5.1.2 on 2024-10-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='title',
        ),
        migrations.RemoveField(
            model_name='course',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='course',
            name='course_name',
            field=models.CharField(help_text='Name of the course', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(help_text='Duration of the course', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='serial_number',
            field=models.CharField(help_text='A unique identifier for the course', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time when the course was created', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, help_text='Optional detailed description of the course', null=True),
        ),
    ]
