# Generated by Django 5.1.2 on 2024-10-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0005_delete_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(help_text='A unique identifier for the course', max_length=50, null=True, unique=True)),
                ('course_name', models.CharField(help_text='Name of the course', max_length=200, null=True)),
                ('duration', models.CharField(help_text='Duration of the course', max_length=100, null=True)),
                ('description', models.TextField(blank=True, help_text='Optional detailed description of the course', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the course was created', null=True)),
            ],
        ),
    ]
