# Generated by Django 5.1.2 on 2024-10-28 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_employee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.AddField(
            model_name='course',
            name='trainer',
            field=models.ForeignKey(blank=True, help_text='The trainer assigned to this course', limit_choices_to={'is_trainer': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
