# Generated by Django 5.1.2 on 2024-11-01 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0012_trainer_remove_course_trainer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='trainer',
            field=models.ForeignKey(help_text='Assigned trainer', limit_choices_to={'username__regex': '^\\d{4}$'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CourseTrainerAssignment',
        ),
        migrations.DeleteModel(
            name='Trainer',
        ),
    ]
