# Generated by Django 5.1.2 on 2024-11-01 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0014_alter_course_trainer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='trainer',
        ),
    ]
