# Generated by Django 5.1.2 on 2024-11-02 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0019_alter_course_course_name_alter_course_duration_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
