# Generated by Django 5.1.3 on 2024-12-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0024_corporatetraininginquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=10)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('participants', models.PositiveIntegerField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='CorporateTrainingInquiry',
        ),
    ]
